version: "3.2"
services:
  livebundle-store:
    build:
      context: .
      dockerfile: packages/livebundle-store/Dockerfile.dev
    labels:
      - traefik.http.routers.livebundle-store.rule=PathPrefix(`/`)
  livebundle-github-consumer:
    build:
      context: .
      dockerfile: packages/livebundle-github-consumer/Dockerfile.dev
    depends_on:
      - livebundle-qrcode
      - livebundle-store
      - queue
  livebundle-github-producer:
    build:
      context: .
      dockerfile: packages/livebundle-github-producer/Dockerfile.dev
    labels:
      - traefik.http.routers.livebundle-github-producer.rule=PathPrefix(`/github`)
      - traefik.http.middlewares.remove-ghapp-prefix.stripprefix.prefixes=/github
      - traefik.http.middlewares.remove-ghapp-prefix.stripprefix.forceslash=false
      - traefik.http.routers.livebundle-github-producer.middlewares=remove-ghapp-prefix@docker
    depends_on:
      - queue
  livebundle-qrcode:
    build:
      context: .
      dockerfile: packages/livebundle-qrcode/Dockerfile.dev
    labels:
      - traefik.http.routers.livebundle-qrcode.rule=PathPrefix(`/qrcode`)
      - traefik.http.middlewares.remove-qrcode-prefix.stripprefix.prefixes=/qrcode
      - traefik.http.middlewares.remove-qrcode-prefix.stripprefix.forceslash=false
      - traefik.http.routers.livebundle-qrcode.middlewares=remove-qrcode-prefix@docker
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  queue:
    image: rabbitmq:3.8
    hostname: livebundle-rabbit
    ports:
      - "5672:5672"
