# QRCode generation configuration
qrcode:
  term:
    # Indicates whether to generate a QR Code in the terminal
    generate: true
    # Indicates whether to generate a small QR Code
    small: true
  image:
    # Indicates whether to generate a QR Code image
    generate: true
    # Margin around QR code image
    margin: 1
    # Width of QR code image (also height given QR Code is a square)
    width: 250
    # Indicates whether to open the image after generation
    open: true

# SDK task configuration
task:
  bundle:
    - dev: true
      entry: index.js
      platform: ios
    - dev: false
      entry: index.js
      platform: ios
    - dev: true
      entry: index.js
      platform: android
    - dev: false
      entry: index.js
      platform: android
  # Store configuration
  #upload:
  # Azure blob storage store configuration
  # There is no default value here
  # Replace them with your own
  #
  # We recommend using env variables here rather
  # than YAML configuration, to limit exposure
  # especially for the SAS token.
  # The corresponding env variables are :
  # account   => LB_UPLOAD_AZURE_ACCOUNT
  # container => LB_UPLOAD_AZURE_CONTAINER
  # sasToken  => LB_UPLOAD_AZURE_SASTOKEN
  #azure:
  #  account: <azure-store-account-name>
  #  container: <azure-store-container-name>
  #  sasToken: <azure-shared-access-signature-token>
  # Notifier configuration
  # We recommend using env variable here rather than
  # YAML configuration, for the gitHubToken
  # token   => LB_NOTIFY_GITHUB_TOKEN
  #notify:
  #  github:
  #    baseUrl: https://api.github.com
  #    token: <github-token>
