# LiveBundle configuration
# Note that some components do not expose any configuration
# but need to declared in the configuration to be activated
# For example, the deep link generator does not have any
# configuration, but declaring it in the configuration
# causes its activation

#
# JavaScript bundler configuration
# Only one bundler can be specified
# Only used for 'upload' command
bundler:
  # Metro bundler configuration
  #
  metro:
    # Bundles to generate and include in the LiveBundle package
    bundles:
      - dev: true
        entry: index.js
        platform: android
      - dev: true
        entry: index.js
        platform: ios

# React Native server configuration
# Only used for 'live' command
server:
  # Metro  server configuration
  #
  metro:

#
# Storage provider configuration
# Only one storage provider can be specified
storage:
  # File system storage provider configuration
  # Comment or remove this whole section when using
  # a different storage provider
  #
  fs:
    # Local directory for storage
    # No setting a path will use a temporary directory
    storageDir: ~/.livebundle/storage

  # Azure blob storage provider configuration
  # We recommend using env variables here instead of
  # YAML configuration, to limit exposure
  # especially for the SAS token.
  # The corresponding env variables are :
  # accountUrl    => LB_STORAGE_AZURE_ACCOUNTURL
  # container     => LB_STORAGE_AZURE_CONTAINER
  # sasToken      => LB_STORAGE_AZURE_SASTOKEN
  # sasTokenReads => LB_STORAGE_AZURE_SASTOKENREADS
  #
  #azure:
  #  accountUrl: <azure-store-account-url>
  #  container: <azure-container-name>
  #  sasToken: <azure-shared-access-signature-token-for-uploads>
  #  sasTokenReads: <azure-sastoken-for-reads>

#
# Generators configuration
# One or more generator(s) can be specified
generators:
  # QR Code generator configuration
  #
  qrcode:
    # Margin around QR code image
    margin: 1
    # Width of QR code image (QR Code is a square)
    width: 250

  # Deep Link generator configuration
  #
  deeplink:

#
# Notifiers configuration
notifiers:
  # Terminal notifier configuration
  #
  terminal:

  # Viewer notifier configuration
  #
  viewer:

  #
  # GitHub notifier configuration
  # We recommend using env variable here rather than
  # YAML configuration, for the token
  # The corresponding env variables is :
  # token => LB_NOTIFIER_GITHUB_TOKEN
  #
  #github:
  #  baseUrl: https://api.github.com
  #  token: <github-token>
