# Sample LiveBundle configuration will all fields

# QRCode generation configuration
qrcode:
  term:
    # Indicates whether to generate a QR Code in the terminal
    generate: true
    # Indicates whether to generate a small QR Code
    small: true
  image:
    # Indicates whether to generate a QR Code image
    generate: true
    # Margin around QR code image
    margin: 1
    # Width of QR code image (also height given QR Code is a square)
    width: 250
    # Indicates whether to open the image after generation
    open: true

# SDK task configuration
task:
  bundle:
    - dev: true
      entry: index.js
      platform: ios
    - dev: false
      entry: index.js
      platform: ios
    - dev: true
      entry: index.js
      platform: android
    - dev: false
      entry: index.js
      platform: android
  # Store configuration
  upload:
    # Azure blob storage store configuration
    # There is no default value here
    # Replace them with your own
    #
    # We recommend using env variables here rather
    # than YAML configuration, to limit exposure
    # mostly for the SAS token.
    # The corresponding env variables are :
    # account   => LB_UPLOAD_AZURE_ACCOUNT
    # container => LB_UPLOAD_AZURE_CONTAINER
    # sasToken  => LB_UPLOAD_AZURE_SASTOKEN
    azure:
      account: foo
      container: bar
      sasToken: ?sv=2019-12-12&ss=b&srt=o&sp=rwacx&se=2020-12-04T09:56:02Z&st=2020-08-07T00:56:02Z&spr=https&sig=8bKcsMbeeKXGnx4NBMjIYU%2FZGAWOAn32YhlmmwW1ZPg%3D
      # If upload has to go through a proxy
      options:
        proxyOptions:
          host: http://myproxy.domain.com
          port: 8080
  # Notifier configuration
  # For use in CI environment when triggering LiveBundle on PRs
  # We recommend using env variable here rather than
  # YAML configuration, for the gitHubToken
  # token to limit exposure.
  # The corresponding env variable is :
  # token => LB_NOTIFY_GITHUB_TOKEN
  notify:
    github:
      baseUrl: https://api.github.com
      token: 7b279319589f286054cd823caefee7a27fa921ea
