# Globs of files to ignore.
# If a PR only contains changed files that are matching
# these globs, LiveBundle will not trigger JS bundling.
ignore:
  [
    "android/**",
    "ios/**",
    "__tests__/**",
    ".buckconfig",
    ".eslintrc.js",
    ".flowconfig",
    ".gitattributes",
    ".gitignore",
    ".prettierrc.js",
    "**/*.md",
  ]

# LiveBundle QR Code service configuration
qrcode:
  url: http://livebundle-qrcode:3000
  margin: 1
  width: 250

# SDK configuration
task:
  prepare:
    steps:
      - yarn install
  bundle:
    - dev: true
      entry: index.js
      platform: ios
    - dev: false
      entry: index.js
      platform: ios
    - dev: true
      entry: index.js
      platform: android
    - dev: false
      entry: index.js
      platform: android
  # LiveBundle Store service configuration
  upload:
    # Store access key
    # accessKey:
    # Store url
    url: http://livebundle-store:3000

# Server configuration
server:
  host: 0.0.0.0
  port: 3000

# AMQP queue configuration
queue:
  url: amqp://queue:5672
  name: livebundle
