name: Release to npm

on:
  workflow_dispatch:

jobs:
  release-ern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release
        run: lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
